services:
  ovolt-php:
    container_name: ovolt-php
    build:
      dockerfile: ./docker/php/Dockerfile
      context: ./
      args:
        PHP_IMAGE: ${PHP_IMAGE}
    restart: always
    working_dir: /application
    volumes:
      - ./:/application:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    networks:
      ovolt-network:

  ovolt-nginx:
    container_name: ovolt-nginx
    image: ${NGINX_IMAGE}
    ports:
      - ${NGINX_EXTERNAL_IP}:${NGINX_EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}
    restart: always
    depends_on:
      - ovolt-php
    volumes:
      - ./:/application:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      ovolt-network:

  ovolt-mysql:
    container_name: ovolt-mysql
    image: ${MYSQL_IMAGE}
    ports:
      - ${MYSQL_EXTERNAL_IP}:${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}
    volumes:
      - ovolt_mysql:/var/lib/mysql
    environment:
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    hostname: ${MYSQL_INTERNAL_HOSTNAME}
    networks:
      ovolt-network:

networks:
    ovolt-network:
        driver: bridge

volumes:
  ovolt_mysql:
